global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "shipment-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:4001"]

  - job_name: "tracking-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:4002"]

  - job_name: "analytics-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:4020"]ule_files:
  - alerts.yml
rule_files:
  - alerts.yml

