apiVersion: v1
kind: Secret
metadata:
  name: shipments-db-secret
  namespace: logistics
type: Opaque
stringData:
  DATABASE_URL: "mysql+pymysql://shipments_user:shipments_pass@host.docker.internal:3308/shipments"
